name: flutter_toeic_quiz2
description: A new Flutter project.

publish_to: "none"

version: 1.0.1+1

environment:
  sdk: ">=2.17.0-182.2.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.0.1
  bloc: ^8.0.3
  percent_indicator: ^3.4.0
  audioplayers: ^0.20.1
  firebase_storage: ^10.2.15
  firebase_core: ^1.16.0
  firebase_core_platform_interface: 4.5.1
  flutter_staggered_grid_view: ^0.6.1
  hive: ^2.2.1
  path_provider: ^2.0.8
  permission_handler: ^8.3.0
  get_it: ^7.2.0
  dynamic_color: ^1.4.0
  google_fonts: ^3.0.1
  shared_preferences: ^2.0.15
  flutter_screenutil: ^5.5.3+2
  flutter_html: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  hive_generator: ^1.1.2
  build_runner: ^2.1.7

flutter:
  uses-material-design: true

  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg